# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/panelplay',
                'doc_host': 'https://fenke.github.io',
                'git_url': 'https://github.com/fenke/panelplay',
                'lib_path': 'panelplay'},
  'syms': {'panelplay.core': {'panelplay.core.foo': ('core.html#foo', 'panelplay/core.py')}}}
